development:
  adapter: postgresql
  database: bad_apples_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bad_apples_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bad_apples_production
  pool: 5
  timeout: 5000
