production:
  :address: smtp.sendgrid.net
  :port: 587
  :authentication: plain
  :user_name: SENDGRID_USERNAME
  :password: SENDGRID_PASSWORD
  :enable_starttls_auto: true
development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ENV["gmail_username"]
  :password: ENV["gmail_password"]
  :enable_starttls_auto: true