production:
  # :address: smtp.sendgrid.net
  # :port: 587
  # :authentication: plain
  # :user_name: ENV['SENDGRID_USERNAME']
  # :password: ENV['SENDGRID_PASSWORD']
  # # :from: 'Bad Apples Registration'
  # :domain: bad-apples.herokuapp.com
  # :enable_starttls_auto: true
  :port: ENV['MAILGUN_SMTP_PORT']
  :address: ENV['MAILGUN_SMTP_SERVER']
  :user_name: ENV['MAILGUN_SMTP_LOGIN']
  :password: ENV['MAILGUN_SMTP_PASSWORD']
  :domain: bad-apples.herokuapp.com
  :authentication: plain
development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: ENV["gmail_username"]
  :password: ENV["gmail_password"]
  :enable_starttls_auto: true